Repository googleapis/python-storage, pull requests merged in 2020-05, with the labels that each got.

#125 feat: add offset and includeTrailingPrefix options to list_blobs
  google/cloud/storage/bucket.py
  google/cloud/storage/client.py
  tests/system/test_system.py
  tests/unit/test_bucket.py
  tests/unit/test_client.py
Labels: cla: yes

#135 feat: Create CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#140 chore(storage): fix lint error in _signing.py module
  google/cloud/storage/_signing.py
Labels: automerge, cla: yes

#133 chore: enable context-aware commits
  synth.py
Labels: cla: yes

#123 feat: add if*generation*Match support, pt1
  google/cloud/storage/_helpers.py
  google/cloud/storage/blob.py
  google/cloud/storage/bucket.py
  google/cloud/storage/client.py
  tests/system/test_system.py
  tests/unit/test__helpers.py
  tests/unit/test_blob.py
  tests/unit/test_bucket.py
  tests/unit/test_client.py
Labels: api: storage, cla: yes, type: feature request

#146 fix(storage): add projection parameter to blob.reload method
  google/cloud/storage/_helpers.py
  tests/system/test_system.py
  tests/unit/test__helpers.py
Labels: cla: yes

#147 fix(storage): add documentaion of list_blobs with user project
  google/cloud/storage/bucket.py
  google/cloud/storage/client.py
Labels: cla: yes

#150 docs(storage): fix documentation
  google/cloud/storage/bucket.py
Labels: cla: yes

#152 fix(storage): remove unused variables
  google/cloud/storage/_helpers.py
Labels: cla: yes

#153 feat: add Bucket.reload() and Bucket.update() wrappers to restrict generation match args
  google/cloud/storage/bucket.py
  tests/unit/test_bucket.py
Labels: api: storage, automerge, cla: yes, type: feature request

#158 fix(storage): fix upload object with bucket cmek enabled
  google/cloud/storage/blob.py
  tests/system/test_system.py
  tests/unit/test_blob.py
Labels: cla: yes

#161 fix(storage): change the method names in snippets file
  docs/snippets.py
Labels: cla: yes

#137 feat: add helper for bucket bound hostname URLs
  google/cloud/storage/_helpers.py
  google/cloud/storage/blob.py
  google/cloud/storage/bucket.py
  google/cloud/storage/client.py
  tests/unit/test__helpers.py
  tests/unit/test_blob.py
  tests/unit/test_bucket.py
Labels: api: storage, automerge, cla: yes, type: cleanup
