Repository googleapis/python-storage, pull requests merged in 2020-04, with the labels that each got.

#87 feature: V4 Post policies
  google/cloud/storage/_signing.py
  google/cloud/storage/client.py
  tests/system/test_system.py
  tests/unit/__init__.py
  tests/unit/test__signing.py
  tests/unit/test_client.py
  tests/unit/url_signer_v4_test_data.json
Labels: cla: yes, type: feature request

#95 fix(storage): use OrderedDict while encoding POST policy
  google/cloud/storage/client.py
  tests/unit/test_client.py
Labels: api: storage, cla: yes

#96 test: update conformance tests to fit the new format
  tests/unit/test__signing.py
  tests/unit/test_client.py
  tests/unit/url_signer_v4_test_data.json
Labels: api: storage, cla: yes, testing

#99 tests: add blobs retention policy discarding into TestRetentionPolicy…
  tests/system/test_system.py
Labels: api: storage, cla: yes, testing

#103 docs(storage): fix docs for new sphinx version
  docs/conf.py
Labels: cla: yes

#106 fix(storage): remove expiration strict conversion
  google/cloud/storage/_signing.py
  tests/unit/test__signing.py
Labels: automerge, cla: yes

#89 docs(storage): add documentation for blob and bucket name property
  google/cloud/storage/blob.py
  google/cloud/storage/bucket.py
Labels: automerge, cla: yes

#42 fix(storage): fix incorrect mtime by UTC offset
  google/cloud/storage/_helpers.py
  google/cloud/storage/blob.py
  tests/unit/test_blob.py
Labels: cla: yes

#104 refactor(storage): deprecate preserve_acl arg in copy_blob() method
  google/cloud/storage/bucket.py
Labels: api: storage, cla: yes, type: bug

#111 feat(storage): add arguments for *GenerationMatch uploading options
  google/cloud/storage/blob.py
  tests/system/test_system.py
  tests/unit/test_blob.py
Labels: api: storage, cla: yes, type: feature request

#91 [CHANGE ME] Re-generated to pick up changes in the API or client library generator.
  .coveragerc
  .flake8
  .github/ISSUE_TEMPLATE/bug_report.md
  CONTRIBUTING.rst
  MANIFEST.in
  setup.cfg
  synth.metadata
Labels: cla: yes

#115 test: update conformance tests for V4 POST policies
  tests/unit/url_signer_v4_test_data.json
Labels: api: storage, cla: yes, testing

#107 fix(storage): anonymous credentials for private bucket
  google/cloud/storage/blob.py
  tests/unit/test_blob.py
  tests/unit/test_client.py
Labels: cla: yes

#118 fix: add bucket name into POST policy conditions
  google/cloud/storage/client.py
  tests/unit/test_client.py
  tests/unit/url_signer_v4_test_data.json
Labels: api: storage, cla: yes, priority: p1, type: bug

#120 test: delete client conformance tests dummy
  tests/unit/test__signing.py
Labels: api: storage, cla: yes, testing
