Repository googleapis/python-storage, pull requests merged in 2020-11, with the labels that each got.

#305 tests: bump max retries for 429/503
  tests/system/test_system.py
Labels: api: storage, cla: yes

#306 tests: normailze systest data paths for Windows
  tests/system/test_system.py
Labels: api: storage, automerge, cla: yes

#298 fix: preserve metadata value
  google/cloud/storage/blob.py
  tests/unit/test_blob.py
Labels: automerge, cla: yes

#290 fix: from_string method of blob and bucket class
  google/cloud/storage/blob.py
  google/cloud/storage/client.py
  tests/unit/test_blob.py
Labels: automerge, cla: yes

#284 tests: cover 'Blob.download_as_string' when no hash matches
  tests/unit/test_blob.py
Labels: automerge, cla: yes

#310 tests: avoid depending on hash order
  tests/unit/test_blob.py
Labels: api: storage, cla: yes

#313 feat: add testing for Python 3.9, drop Python 3.5
  noxfile.py
  synth.metadata
Labels: api: storage, cla: yes, context: none

#295 feat: add classifiers for python3.9 and remove for python3.5
  setup.py
Labels: automerge, cla: yes

#308 tests: add explicit coverage for retry members
  noxfile.py
  synth.py
  tests/unit/test_retry.py
Labels: api: storage, automerge, cla: yes

#316 fix: retry uploads only conditionally
  google/cloud/storage/blob.py
  tests/unit/test_blob.py
Labels: api: storage, cla: yes

#323 fix: add change in 'Blob.custom_time' to changes
  google/cloud/storage/blob.py
  tests/unit/test_blob.py
Labels: api: storage, cla: yes

#317 chore: blacken 'noxfile.py'
  noxfile.py
  synth.metadata
Labels: api: storage, cla: yes, context: none

#326 fix: fall back to 'charset' of 'content_type' in 'download_as_text'
  google/cloud/storage/blob.py
  tests/unit/test_blob.py
Labels: api: storage, cla: yes
