Repository googleapis/python-storage, pull requests merged in 2020-02, with the labels that each got.

#43 fix(storage): fix documentation of max_result parameter in list_blob
  google/cloud/storage/bucket.py
  google/cloud/storage/client.py
Labels: cla: yes

#45 chore: bump google-auth dependency to v1.11.0+
  setup.py
Labels: cla: yes, type: process

#44 feat: add timeout parameter to public methods
  google/cloud/storage/_helpers.py
  google/cloud/storage/acl.py
  google/cloud/storage/batch.py
  google/cloud/storage/blob.py
  google/cloud/storage/bucket.py
  google/cloud/storage/client.py
  google/cloud/storage/constants.py
  google/cloud/storage/hmac_key.py
  google/cloud/storage/notification.py
  tests/unit/test__helpers.py
  tests/unit/test__http.py
  tests/unit/test_acl.py
  tests/unit/test_batch.py
  tests/unit/test_blob.py
  tests/unit/test_bucket.py
  tests/unit/test_client.py
  tests/unit/test_hmac_key.py
  tests/unit/test_notification.py
Labels: cla: yes, type: feature request

#53 fix(tests): remove low version error assertion from iam conditions system tests
  tests/system.py
Labels: cla: yes

#47 fix(storage): fix system test and change scope for iam access token
  tests/system.py
Labels: cla: yes

#49 refactor(storage): deprecate Bucket.create() and requester_pays
  docs/snippets.py
  google/cloud/storage/bucket.py
  google/cloud/storage/client.py
  tests/unit/test_bucket.py
  tests/unit/test_client.py
Labels: cla: yes, type: feature request

#51 tests: move system tests into a package
  tests/system/test_system.py
Labels: api: storage, cla: yes, type: process

#56 fix: make v4 signing formatting consistent w/ spec
  google/cloud/storage/_signing.py
  tests/unit/test__signing.py
Labels: api: storage, cla: yes

#60 fix(storage): fix blob metadata to None regression
  google/cloud/storage/blob.py
  tests/unit/test_blob.py
Labels: cla: yes, type: bug

#58 feat: generate signed URLs for blobs/buckets using virtual hostname
  google/cloud/storage/blob.py
  google/cloud/storage/bucket.py
  tests/unit/test_blob.py
  tests/unit/test_bucket.py
Labels: cla: yes

#63 fix: add classifer for Python 3.8
  noxfile.py
  setup.py
  tests/system/test_system.py
  tests/unit/test_blob.py
  tests/unit/test_bucket.py
Labels: cla: yes

#62 test: use a live endpoint for performance benchmarks
  .kokoro/continuous/storage_perf_bench.cfg
  tests/perf/benchwrapper.py
Labels: cla: yes

#71 fix: use correct IAM object admin role
  google/cloud/storage/iam.py
Labels: cla: yes, type: bug

#65 chore: update to latest black (via synth)
  docs/conf.py
  synth.metadata
Labels: cla: yes
