Repository googleapis/python-storage, pull requests merged in 2020-07, with the labels that each got.

#193 chore: update templates
  .flake8
  .gitignore
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/samples/lint/common.cfg
  .kokoro/samples/lint/continuous.cfg
  .kokoro/samples/lint/periodic.cfg
  .kokoro/samples/lint/presubmit.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.6/continuous.cfg
  .kokoro/samples/python3.6/periodic.cfg
  .kokoro/samples/python3.6/presubmit.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.7/continuous.cfg
  .kokoro/samples/python3.7/periodic.cfg
  .kokoro/samples/python3.7/presubmit.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/samples/python3.8/continuous.cfg
  .kokoro/samples/python3.8/periodic.cfg
  .kokoro/samples/python3.8/presubmit.cfg
  .kokoro/test-samples.sh
  MANIFEST.in
  docs/_templates/layout.html
  docs/conf.py
  google/cloud/storage/blob.py
  noxfile.py
  scripts/decrypt-secrets.sh
  scripts/readme-gen/readme_gen.py
  scripts/readme-gen/templates/README.tmpl.rst
  scripts/readme-gen/templates/auth.tmpl.rst
  scripts/readme-gen/templates/auth_api_key.tmpl.rst
  scripts/readme-gen/templates/install_deps.tmpl.rst
  scripts/readme-gen/templates/install_portaudio.tmpl.rst
  synth.metadata
  synth.py
  testing/.gitignore
  tests/unit/test_blob.py
Labels: cla: yes, context: none

#198 test: add retry for default kms system test
  tests/system/test_system.py
Labels: api: storage, cla: yes, testing

#207 tests: unit tests pass w/o environ vars
  tests/unit/test_client.py
Labels: cla: yes, testing

#209 docs: remove doubled word in docstring
  google/cloud/storage/client.py
Labels: cla: yes

#185 feat: add timeouts to Blob methods where missing
  google/cloud/storage/blob.py
  setup.py
  tests/unit/test_blob.py
Labels: cla: yes

#204 feat(blob.py): auto-populate standard headers for non-chunked downloads
  google/cloud/storage/blob.py
  tests/unit/test_blob.py
Labels: automerge, cla: yes

#212 chore(packaging): prep for grmp-1.0.0 release
  setup.py
Labels: cla: yes, type: process

#217 tests: add unit test to fix coverage
  tests/unit/test_blob.py
Labels: cla: yes

#219 tests: fix the system tests
  tests/system/test_system.py
Labels: cla: yes
