Repository googleapis/python-storage, pull requests merged in 2020-08, with the labels that each got.

#227 testing: fix / skip systests broken by dependency releases
  tests/system/test_system.py
Labels: cla: yes, testing

#222 docs: update docs build (via synth)
  .gitignore
  .kokoro/build.sh
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/publish-docs.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  docs/conf.py
  noxfile.py
  synth.metadata
Labels: api: storage, cla: yes, context: full, type: docs

#225 feat: pass 'client_options' to base class ctor
  google/cloud/storage/client.py
  setup.py
Labels: automerge, cla: yes

#232 tests: pin google-cloud-kms to un-break systests
  noxfile.py
  synth.py
  tests/system/test_system.py
Labels: cla: yes

#182 feat: rename 'Blob.download_as_{string,bytes}', add 'Blob.download_as_text'
  google/cloud/storage/blob.py
  tests/system/test_system.py
  tests/unit/test_blob.py
Labels: cla: yes

#233 chore: add some excludes in docs/conf.py (via synth)
  docs/conf.py
  synth.metadata
Labels: cla: yes, context: full

#242 chore: bump g-c-c to 1.4.1
  setup.py
Labels: cla: yes

#238 fix: extract hashes correctly during download
  google/cloud/storage/blob.py
  tests/system/test_system.py
  tests/unit/test_blob.py
Labels: cla: yes

#245 test: add retry for bucket cmek enabled system test
  tests/system/test_system.py
Labels: cla: yes

#162 feat(storage): add support of daysSinceNoncurrentTime and noncurrentTimeBefore
  google/cloud/storage/bucket.py
  tests/system/test_system.py
  tests/unit/test_bucket.py
Labels: cla: yes

#251 fix: change datetime.now to utcnow
  tests/system/test_system.py
Labels: api: storage, automerge, cla: yes

#235 feat: error message return from api
  google/cloud/storage/blob.py
  tests/unit/test_blob.py
Labels: api: storage, cla: yes

#199 feat: add support for 'Blob.custom_time' and lifecycle rules
  google/cloud/storage/blob.py
  google/cloud/storage/bucket.py
  tests/system/test_system.py
  tests/unit/test_blob.py
  tests/unit/test_bucket.py
Labels: cla: yes

#246 feat: add configurable checksumming for blob uploads and downloads
  google/cloud/storage/blob.py
  setup.py
  tests/system/test_system.py
  tests/unit/test_blob.py
Labels: api: storage, cla: yes

#255 fix: repair mal-formed docstring
  google/cloud/storage/blob.py
Labels: cla: yes

#250 docs: add docs signed_url expiration take default utc
  google/cloud/storage/_signing.py
  google/cloud/storage/blob.py
  google/cloud/storage/bucket.py
  google/cloud/storage/client.py
Labels: api: storage, cla: yes

#259 chore: start tracking obsolete files
  synth.metadata
Labels: api: storage, cla: yes, context: full
