Repository googleapis/python-storage, pull requests merged in 2020-09, with the labels that each got.

#258 fix(blob): base64 includes additional characters
  google/cloud/storage/blob.py
  tests/unit/test_blob.py
Labels: api: storage, automerge, cla: yes

#273 chore: restrict pubsub to < 2.0
  noxfile.py
  synth.py
Labels: api: storage, cla: yes

#271 fix: add requests as a dependency
  setup.py
Labels: api: storage, cla: yes

#267 fix: preserve existing blob hashes when 'X-Goog-Hash header' is not present
  google/cloud/storage/blob.py
  tests/unit/test_blob.py
Labels: api: storage, cla: yes

#278 docs: fix docstring example for 'blob.generate_signed_url'
  google/cloud/storage/blob.py
Labels: api: storage, cla: yes

#265 chore: enable snippet-bot
  .github/snippet-bot.yml
  synth.metadata
Labels: api: storage, cla: yes, context: full

#280 chore: skip reporting coverage for namespace package, update secrets manager (via synth)
  .coveragerc
  .kokoro/populate-secrets.sh
  .kokoro/release/common.cfg
  .kokoro/trampoline.sh
  CONTRIBUTING.rst
  docs/conf.py
  noxfile.py
  scripts/decrypt-secrets.sh
  synth.metadata
Labels: cla: yes, context: full
