Repository googleapis/python-storage, pull requests merged in 2020-03, with the labels that each got.

#78 fix(storage): remove docstring of retrun in reload method
  google/cloud/storage/notification.py
Labels: cla: yes

#77 feat(storage): add get notification method
  google/cloud/storage/bucket.py
  google/cloud/storage/notification.py
  tests/system/test_system.py
  tests/unit/test_bucket.py
Labels: cla: yes

#79 docs: fix URL for the old issue
  CHANGELOG.md
Labels: cla: yes, type: docs

#48 feat(storage): improve v4 signature query parameters encoding
  google/cloud/storage/_signing.py
  tests/unit/test__signing.py
Labels: automerge, cla: yes, type: feature request

#75 docs(storage): add description and example to retrieve the hash of blob
  google/cloud/storage/blob.py
Labels: automerge, cla: yes

#72 feat(storage): Add cname support for V4 signature
  google/cloud/storage/_signing.py
  google/cloud/storage/blob.py
  google/cloud/storage/bucket.py
  tests/unit/test__signing.py
  tests/unit/test_blob.py
  tests/unit/test_bucket.py
  tests/unit/url_signer_v4_test_data.json
Labels: cla: yes

#83 feat(storage): add conformance tests for virtual hosted style signed URLs
  tests/unit/test__signing.py
  tests/unit/url_signer_v4_test_data.json
Labels: cla: yes

#85 docs(storage): few spelling fixes for generate_signed_url()
  google/cloud/storage/blob.py
Labels: cla: yes, type: docs

#84 Fix typo in docs: paramters -> parameters
  google/cloud/storage/_signing.py
  google/cloud/storage/bucket.py
  tests/unit/test__signing.py
Labels: automerge, cla: yes

#81 refactor(storage): consistent use of optional keyword
  google/cloud/storage/_helpers.py
  google/cloud/storage/_signing.py
  google/cloud/storage/acl.py
  google/cloud/storage/batch.py
  google/cloud/storage/blob.py
  google/cloud/storage/bucket.py
  google/cloud/storage/client.py
  google/cloud/storage/hmac_key.py
  google/cloud/storage/notification.py
Labels: automerge, cla: yes
