Repository googleapis/python-storage, pull requests merged in 2021-08, with the labels that each got.

#531 chore: require CODEOWNER review and up to date branches
  .github/sync-repo-settings.yaml
Labels: api: storage, automerge, cla: yes

#530 fix(deps): add explicit ranges for 'google-api-core' and 'google-auth'
  setup.py
  testing/constraints-3.6.txt
Labels: api: storage, cla: yes, automerge

#534 chore: drop use of 'pytz' in tests / examples
  google/cloud/storage/client.py
  tests/unit/test__signing.py
  tests/unit/test_bucket.py
  tests/unit/test_client.py
  tests/unit/test_hmac_key.py
Labels: api: storage, cla: yes

#539 chore: generate python samples templates in owlbot.py
  owlbot.py
Labels: api: storage, cla: yes, automerge, samples

#450 tests: add retry conformance test framework and test always idempotent operations
  noxfile.py
  tests/conformance/__init__.py
  tests/conformance/retry_strategy_test_data.json
  tests/conformance/test_conformance.py
  tests/unit/test__signing.py
Labels: api: storage, cla: yes

#545 docs: pass explicit 'client' in '{Blob.Bucket}.from_string' examples
  google/cloud/storage/blob.py
  google/cloud/storage/bucket.py
  google/cloud/storage/client.py
  tests/unit/test_client.py
Labels: api: storage, type: docs, cla: yes, automerge

#550 tests: add retry for 400 from 'Bucket.update' after removing labels
  tests/system/test_bucket.py
Labels: api: storage, cla: yes

#552 tests: harden 'test_bucket_w_retention_period' vs EC
  tests/system/test_bucket.py
Labels: api: storage, cla: yes

#548 tests: further harden blob teardown against EBH
  tests/system/_helpers.py
Labels: api: storage, cla: yes

#560 chore(revert): update dependency google-cloud-core to v2
  setup.py
Labels: api: storage, cla: yes

#563 chore: migrate to main branch
  .github/sync-repo-settings.yaml
  .kokoro/build.sh
  .kokoro/test-samples-impl.sh
  CONTRIBUTING.rst
  owlbot.py
Labels: api: storage, cla: yes
