Repository googleapis/python-storage, pull requests merged in 2024-07, with the labels that each got.

#1306 test: add check in pytest fixture
  tests/system/conftest.py
Labels: api: storage, size: xs

#1298 test: enable retries for blobwriter tests
  tests/system/test_fileio.py
Labels: api: storage, size: xs

#1297 chore: update blunderbuss assignment
  .github/blunderbuss.yml
  owlbot.py
Labels: api: storage, size: s

#1317 fix: Allow Protobuf 5.x
  setup.py
Labels: api: storage, size: xs

#1283 feat: resumable media integration
  README.rst
  docs/storage/exceptions.rst
  google/cloud/storage/_helpers.py
  google/cloud/storage/_media/__init__.py
  google/cloud/storage/_media/_download.py
  google/cloud/storage/_media/_helpers.py
  google/cloud/storage/_media/_upload.py
  google/cloud/storage/_media/common.py
  google/cloud/storage/_media/requests/__init__.py
  google/cloud/storage/_media/requests/_request_helpers.py
  google/cloud/storage/_media/requests/download.py
  google/cloud/storage/_media/requests/upload.py
  google/cloud/storage/blob.py
  google/cloud/storage/exceptions.py
  google/cloud/storage/transfer_manager.py
  noxfile.py
  setup.py
  tests/resumable_media/system/requests/conftest.py
  tests/resumable_media/system/requests/test_download.py
  tests/resumable_media/system/requests/test_upload.py
  tests/resumable_media/unit/requests/test__helpers.py
  tests/resumable_media/unit/requests/test_download.py
  tests/resumable_media/unit/requests/test_upload.py
  tests/resumable_media/unit/test__download.py
  tests/resumable_media/unit/test__helpers.py
  tests/resumable_media/unit/test__upload.py
  tests/resumable_media/unit/test_common.py
  tests/system/test_blob.py
  tests/unit/test_blob.py
  tests/unit/test_client.py
  tests/unit/test_exceptions.py
  tests/unit/test_transfer_manager.py
Labels: api: storage, size: l

#1323 test: harden pytest fixture setup stage
  tests/system/conftest.py
Labels: api: storage, size: s

#1328 docs: Fix issue with exceptions.py documentation
  docs/index.rst
  docs/storage/exceptions.rst
Labels: api: storage
