Repository googleapis/python-storage, pull requests merged in 2025-03, with the labels that each got.

#1444 chore: remove unused files
  .github/.OwlBot.lock.yaml
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/docker/docs/requirements.in
  .kokoro/docker/docs/requirements.txt
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/docs/docs.cfg
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/release/common.cfg
  .kokoro/release/release.cfg
  .kokoro/requirements.in
  .kokoro/requirements.txt
Labels: api: storage, size: xl

#1445 fix: allow Protobuf 6.x
  .kokoro/continuous/prerelease-deps.cfg
  .kokoro/presubmit/prerelease-deps.cfg
  CONTRIBUTING.rst
  noxfile.py
  owlbot.py
  samples/snippets/noxfile_config.py
  setup.py
  testing/constraints-3.13.txt
  testing/constraints-3.7.txt
  tests/system/test_notification.py
Labels: api: storage, size: m

#1447 chore: update changelog to add credit and detail to a past security-related bugfix
  CHANGELOG.md
Labels: api: storage, size: xs

#1450 docs: update README to break infinite redirect loop
  README.rst
Labels: api: storage, size: xs

#1454 chore: remove andrewsg from blunderbuss
  .github/blunderbuss.yml
Labels: api: storage, automerge, size: xs
