Repository googleapis/python-storage, pull requests merged in 2025-07, with the labels that each got.

#1493 feat: Adding support of single shot download
  google/cloud/storage/_media/_download.py
  google/cloud/storage/_media/requests/download.py
  google/cloud/storage/blob.py
  google/cloud/storage/client.py
  google/cloud/storage/fileio.py
  tests/resumable_media/system/requests/test_download.py
  tests/resumable_media/unit/requests/test_download.py
  tests/system/test_blob.py
  tests/unit/test_blob.py
  tests/unit/test_client.py
Labels: api: storage, size: l

#1497 chore: update the source path in owlbot.yaml
  .github/.OwlBot.yaml
Labels: api: storage, size: xs

#1500 tests: update constraints for python 3.9 testing
  testing/constraints-3.9.txt
Labels: api: storage, size: s

#1501 build: exclude certain autogenerated files
  owlbot.py
Labels: api: storage, size: xs

#1503 chore: fix the errors while generating gapic
  noxfile.py
  owlbot.py
Labels: api: storage, size: xs

#1504 chore: fix the module imports error for gapic
  noxfile.py
  owlbot.py
Labels: api: storage, size: xs

#1507 docs: update the documentation of move_blob function
  google/cloud/storage/bucket.py
Labels: api: storage, size: xs

#1509 chore: fix the errors for GAPIC
  .coveragerc
  noxfile.py
  owlbot.py
  testing/constraints-3.9.txt
Labels: api: storage, size: s

#1511 chore: remove duplicates in coveragerc
  .coveragerc
Labels: api: storage, size: xs

#1517 chore: improve docs for list_files_with_prefix
  samples/snippets/storage_list_files_with_prefix.py
Labels: api: storage, samples, size: s
